apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-factory-autohide-service
  namespace: model-factory-services
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 900
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 180
      template:
        spec:
          serviceAccountName: model-factory-service-sa
          containers:
          - name: model-factory-autohide-service
            image: $DOCKER_REGISTRY/model-factory-autohide-service
            imagePullPolicy: Always
          restartPolicy: Never
