apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: model-factory-frontend
    meta.helm.sh/release-namespace: model-factory-services
  labels:
    app.kubernetes.io/instance: model-factory-frontend
  name: model-factory-frontend
  namespace: model-factory-services
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: model-factory-frontend
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: model-factory-frontend
    spec:
      serviceAccountName: model-factory-service-sa
      containers:
      - env:
        - name: LOG_LEVEL
          value: INFO
        image: $DOCKER_REGISTRY/model-factory-frontend:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /bin/sleep 45
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /keepalive
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: model-factory-frontend
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /keepalive
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: model-factory-service-sa
  namespace: model-factory-services
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: model-factory-service-clusterrole
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "update", "get", "list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: model-factory-service-rolebinding
subjects:
  - kind: ServiceAccount
    name: model-factory-service-sa
    namespace: model-factory-services
roleRef:
  kind: ClusterRole
  name: model-factory-service-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: model-factory-frontend
  namespace: model-factory-services
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app: model-factory-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
